config/routes.rb
Rails.application.routes.draw do
  get 'carts/show'

  resources :products
  resources :shops, only:[:index,:show]
  resources :order_items
  resource :carts, only:[:show]
  root "shops#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_items
    before_save :set_subtotal


    def subtotal
        order_items.collect{|order_item| order_item.valid? ? order_item.unit_price*order_item.quantity : 0}.sum
    end  
    
    private

    def set_subtotal
        self[:subtotal] = subtotal
    end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  before_save :set_unit_price
  before_save :set_total

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end  
  end

  def total
    unit_price*quantity
  end

  private

  def set_unit_price
    self[:unit_price]=unit_price
  end

  def set_total
    self[:total]=total*quantity
  end



end

app/models/product.rb
class Product < ApplicationRecord
    has_many :order_items


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
include ApplicationHelper
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController

    def create
        @order = current_order
        @order_item= @order.order_items.new(order_params)
        @order.save
        session[:order_id]=@order.id
        redirect_to root_path
    end

    def update
        @order=current_order
        @order_item=@order.order_items.find(params[:id])
        @order_item.update(order_params)
        redirect_to root_path
    end

    def destroy
        @order=current_order
        @order_item=@order.order_items.find(params[:id])
        @order_item.destroy
        @order_items= current_order.order_items
        redirect_to root_path
    end
    private
    def order_params
        params.require(:order_item).permit(:product_id,:quantity)

    end     
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :price)
    end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def index
    @products = Product.all
    @order_item= current_order.order_items.new
  end

  def show
    @product=Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def current_order
        if !session[:order_id].nil?
            Order.find(session[:order_id])
        else
            Order.new
        end    

    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/carts/_cart.html.erb
<%= link_to "#{current_order.order_items.size} items with a value of #{current_order.subtotal }$", carts_path%>

app/views/carts/show.html.erb
<h1>Carts#show</h1>
<p>Find me in app/views/carts/show.html.erb</p>

<%@order_items.each do |item|%>
<h3><%=item.product.title%></h3>
<h5><%=item.product.price%></h5>



<%= form_for item do |f|%>
 <%= f.hidden_field :product_id, :value =>item.product.id%>
  <%= f.number_field :quantity, :value =>item.quantity.to_i%>
  <%= f.submit%>

<%end%>

  <%= form_for item, url: order_item_path(item), method: :delete do |f|%>
    <%= f.submit "Delete" %>
      <%end%>

<h2>Subtotal: <%= item.total %></h2>


<%end%>

<h3>Your current cart value has a subtotal of: <%= current_order.subtotal%> </h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Onlineshop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Title:</strong>
    <%= product.title %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>

</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Products</h1>

<div id="products">
  <% @products.each do |product| %>
    <%= render product %>
    <p>
      <%= link_to "Show this product", product %>
    </p>
  <% end %>
</div>

<%= link_to "New product", new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>

app/views/shops/index.html.erb
<h1>Shops#index</h1>
<p>Find me in app/views/shops/index.html.erb</p>
<p style="color: green"><%= notice %></p>

<h1>Products</h1>

<div id="products">
  <% @products.each do |product| %>
    <%= render product %>
    <p>
      <%= link_to "Show this product", shop_path(product) %>
    </p>

  <td>
  <%= form_for @order_item, remote: true do |f|%>
  <%= f.hidden_field :product_id, :value =>product.id%>
  <%= f.number_field :quantity, :value =>1, :min=>1%>
  <%= f.submit%>
<%end%>
  </td>

  <% end %>
</div>

<div id="cart">
<%= render 'carts/cart'%>
</div>

app/views/shops/show.html.erb
<h1>Shops#show</h1>
<p>Find me in app/views/shops/show.html.erb</p>
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>

  <%= link_to "Back to products", root_path %>

</div>